export const qk = {
  me: ["me"] as const,
  settings: ["settings"] as const,
  stats: ["stats"] as const,
  overview: ["stats", "overview"] as const,
  dashboard: (days: number) => ["stats", "dashboard", days] as const,
  mailboxes: ["mailboxes"] as const,
  imapPresets: ["mailboxes", "imap-presets"] as const,
  mailboxConnection: (id: string) => ["mailboxes", "connection", id] as const,
  rules: ["rules"] as const,
  rule: (id: string) => ["rules", "detail", id] as const,
  ruleFields: ["rule-fields"] as const,
  messages: (filters: { mailbox_id?: string; rule_id?: string; q?: string } = {}) =>
    ["messages", "list", filters] as const,
  messagesAll: ["messages"] as const,
  message: (id: string) => ["messages", "detail", id] as const,
  // Outside the "messages" prefix on purpose: it's a live mailbox read, so list invalidations shouldn't refetch it.
  messageContent: (id: string) => ["message-content", id] as const,
  notifications: (status?: string) => ["notifications", "list", status ?? "all"] as const,
  notificationsAll: ["notifications"] as const,
  destinations: ["destinations"] as const,
  templates: ["email-templates"] as const,
  template: (id: string) => ["email-templates", "detail", id] as const,
  templatePreview: (id: string) => ["email-templates", "preview", id] as const,
  outbound: (status?: string) => ["outbound-emails", "list", status ?? "all"] as const,
  outboundAll: ["outbound-emails"] as const,
  outboundEmail: (id: string) => ["outbound-emails", "detail", id] as const,
  events: (filters: { status?: string[]; from?: string; to?: string } = {}) => ["events", "list", filters] as const,
  eventsAll: ["events"] as const,
  eventLists: ["events", "list"] as const,
  calendarFeed: ["events", "calendar-feed"] as const,
  rulePacks: ["rules", "packs"] as const,
  ruleSuggestions: (mailboxId: string) => ["rule-suggestions", mailboxId] as const,
  onboarding: ["onboarding"] as const,
  aiStatus: ["ai", "status"] as const,
  aiReplyIdeas: (messageId: string, guidance = "") => ["ai", "reply-ideas", messageId, guidance] as const,
  adminWaha: ["admin", "waha"] as const,
  adminQueues: ["admin", "queues"] as const,
};
