"""udated use of ENUM

Revision ID: b7ad293e1f68
Revises: 58a88d897018
Create Date: 2025-10-12 18:35:16.852937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7ad293e1f68'
down_revision: Union[str, None] = '58a88d897018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    email_digest_enum = sa.Enum('DAILY', 'WEEKLY', name='emaildigestfrequency')
    email_digest_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
               'notification_preferences',
               'email_digest_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=email_digest_enum,
               existing_nullable=False,
               postgresql_using="email_digest_frequency::emaildigestfrequency")
    # ### end Alembic commands ###


def downgrade() -> None:
    email_digest_enum = sa.Enum('DAILY', 'WEEKLY', name='emaildigestfrequency')

    op.alter_column(
        'notification_preferences',
        'email_digest_frequency',
        existing_type=email_digest_enum,
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        postgresql_using='email_digest_frequency::text'
    )

    email_digest_enum.drop(op.get_bind(), checkfirst=True)
