"""init

Revision ID: e60b24afc607
Revises: e0b5021aeace
Create Date: 2025-10-24 00:35:41.795335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60b24afc607'
down_revision: Union[str, None] = 'e0b5021aeace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_emails', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('connected_emails', sa.Column('last_history_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_emails', 'last_history_id')
    op.drop_column('connected_emails', 'created_at')
    # ### end Alembic commands ###
