"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 18:15:04.654131
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='role', native_enum=False, length=32), server_default='user', nullable=False),
    sa.Column('plan', sa.String(length=32), server_default='free', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_e164', name=op.f('uq_users_phone_e164'))
    )
    op.create_table('destinations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('whatsapp_self', 'whatsapp_number', 'whatsapp_group', name='destinationkind', native_enum=False, length=32), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_destinations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations')),
    sa.UniqueConstraint('user_id', 'chat_id', name=op.f('uq_destinations_user_id'))
    )
    op.create_index(op.f('ix_destinations_user_id'), 'destinations', ['user_id'], unique=False)
    op.create_table('mailboxes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'imap', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'reauth_required', 'error', name='mailboxstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('credentials', sa.LargeBinary(), nullable=False),
    sa.Column('sync_cursor', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('watch_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('messages_scanned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mailboxes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailboxes')),
    sa.UniqueConstraint('user_id', 'provider', 'address', name=op.f('uq_mailboxes_user_id'))
    )
    op.create_index('ix_mailboxes_provider_address', 'mailboxes', ['provider', 'address'], unique=False)
    op.create_index(op.f('ix_mailboxes_user_id'), 'mailboxes', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('stop_processing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mailbox_ids', sa.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('match_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index('ix_rules_user_position', 'rules', ['user_id', 'position'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('digest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=True),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('messages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=320), nullable=True),
    sa.Column('to_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('list_id', sa.String(length=320), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('web_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_messages_mailbox_id_mailboxes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('mailbox_id', 'provider_message_id', name=op.f('uq_messages_mailbox_id'))
    )
    op.create_index('ix_messages_user_received', 'messages', ['user_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('alert', 'digest', 'system', 'verification', name='notificationkind', native_enum=False, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'delivered', 'read', 'held', 'folded', 'failed', 'dead', name='notificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('held_reason', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_notifications_destination_id_destinations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_notifications_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['notifications.id'], name=op.f('fk_notifications_parent_id_notifications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    op.create_index('ix_notifications_due', 'notifications', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status IN ('queued', 'failed')"))
    op.create_index('ix_notifications_held', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text("status = 'held'"))
    op.create_index(op.f('ix_notifications_provider_message_id'), 'notifications', ['provider_message_id'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('rule_matches',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_rule_matches_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_matches_rule_id_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_matches')),
    sa.UniqueConstraint('message_id', 'rule_id', name=op.f('uq_rule_matches_message_id'))
    )
    op.create_index(op.f('ix_rule_matches_message_id'), 'rule_matches', ['message_id'], unique=False)
    op.create_index(op.f('ix_rule_matches_rule_id'), 'rule_matches', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_matches_rule_id'), table_name='rule_matches')
    op.drop_index(op.f('ix_rule_matches_message_id'), table_name='rule_matches')
    op.drop_table('rule_matches')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_provider_message_id'), table_name='notifications')
    op.drop_index('ix_notifications_held', table_name='notifications', postgresql_where=sa.text("status = 'held'"))
    op.drop_index('ix_notifications_due', table_name='notifications', postgresql_where=sa.text("status IN ('queued', 'failed')"))
    op.drop_table('notifications')
    op.drop_index('ix_messages_user_received', table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_settings')
    op.drop_index('ix_rules_user_position', table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_mailboxes_user_id'), table_name='mailboxes')
    op.drop_index('ix_mailboxes_provider_address', table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_destinations_user_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_table('users')
    # ### end Alembic commands ###
