"""whatsapp email compose

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 19:38:40.553162
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('mailbox_id', sa.Uuid(), nullable=True),
    sa.Column('to_addresses', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('cc_addresses', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('bcc_addresses', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_email_templates_mailbox_id_mailboxes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('uq_email_templates_user_id'))
    )
    op.create_index('uq_email_templates_default', 'email_templates', ['user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('outbound_emails',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('to_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('cc_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('bcc_addresses', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('awaiting_confirmation', 'queued', 'sending', 'sent', 'failed', 'cancelled', 'expired', name='outboundstatus', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='whatsapp', nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=True),
    sa.Column('template_name', sa.String(length=40), nullable=True),
    sa.Column('confirm_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_outbound_emails_mailbox_id_mailboxes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_outbound_emails_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_emails'))
    )
    op.create_index('ix_outbound_emails_awaiting', 'outbound_emails', ['user_id'], unique=False, postgresql_where=sa.text("status = 'awaiting_confirmation'"))
    op.create_index('ix_outbound_emails_user_created', 'outbound_emails', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outbound_attachments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.Column('wa_message_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['outbound_emails.id'], name=op.f('fk_outbound_attachments_email_id_outbound_emails'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_outbound_attachments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_attachments')),
    sa.UniqueConstraint('wa_message_id', name=op.f('uq_outbound_attachments_wa_message_id'))
    )
    op.create_index(op.f('ix_outbound_attachments_email_id'), 'outbound_attachments', ['email_id'], unique=False)
    op.create_index('ix_outbound_attachments_staged', 'outbound_attachments', ['user_id'], unique=False, postgresql_where=sa.text('email_id IS NULL'))
    op.add_column('mailboxes', sa.Column('can_send', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_settings', sa.Column('compose_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'compose_enabled')
    op.drop_column('mailboxes', 'can_send')
    op.drop_index('ix_outbound_attachments_staged', table_name='outbound_attachments', postgresql_where=sa.text('email_id IS NULL'))
    op.drop_index(op.f('ix_outbound_attachments_email_id'), table_name='outbound_attachments')
    op.drop_table('outbound_attachments')
    op.drop_index('ix_outbound_emails_user_created', table_name='outbound_emails')
    op.drop_index('ix_outbound_emails_awaiting', table_name='outbound_emails', postgresql_where=sa.text("status = 'awaiting_confirmation'"))
    op.drop_table('outbound_emails')
    op.drop_index('uq_email_templates_default', table_name='email_templates', postgresql_where=sa.text('is_default'))
    op.drop_table('email_templates')
    # ### end Alembic commands ###
