"""deadline radar and alert actions

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 15:04:34.237372
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.Enum('exam', 'interview', 'deadline', 'payment', 'meeting', 'travel', 'other', name='eventkind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('suggested', 'upcoming', 'done', 'dismissed', name='eventstatus', native_enum=False, length=32), nullable=False),
    sa.Column('ics_uid', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_events_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('message_id', 'starts_at', name=op.f('uq_events_message_id'))
    )
    op.create_index('ix_events_user_starts', 'events', ['user_id', 'starts_at'], unique=False)
    op.add_column('messages', sa.Column('ref', sa.String(length=8), nullable=True))
    op.create_index('ix_messages_user_ref', 'messages', ['user_id', 'ref'], unique=False)
    op.add_column('outbound_emails', sa.Column('reply_to_message_id', sa.Uuid(), nullable=True))
    op.add_column('outbound_emails', sa.Column('in_reply_to', sa.String(length=998), nullable=True))
    op.add_column('outbound_emails', sa.Column('references', sa.Text(), nullable=True))
    op.add_column('outbound_emails', sa.Column('provider_thread_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(op.f('fk_outbound_emails_reply_to_message_id_messages'), 'outbound_emails', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    op.add_column('rules', sa.Column('source', sa.String(length=80), nullable=True))
    op.add_column('user_settings', sa.Column('muted_senders', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('user_settings', sa.Column('weekly_recap', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('last_recap_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('deadlines_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('calendar_token', sa.String(length=64), nullable=True))
    op.add_column('user_settings', sa.Column('test_alert_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('onboarding_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(op.f('uq_user_settings_calendar_token'), 'user_settings', ['calendar_token'])
    # ### end Alembic commands ###

    _backfill_refs()


REF_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"


def _encode_ref(n: int) -> str:
    n += len(REF_ALPHABET) - 1
    out = ""
    while n:
        n, r = divmod(n, len(REF_ALPHABET))
        out = REF_ALPHABET[r] + out
    return out


def _backfill_refs() -> None:
    """Give emails caught before this release a WhatsApp code, numbered per user in arrival order.
    (Frozen copy of app.compose.commands.encode_ref so this migration never changes.)"""
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT id, row_number() OVER (PARTITION BY user_id ORDER BY created_at, id) AS n "
        "FROM messages WHERE ref IS NULL")).all()
    for message_id, n in rows:
        conn.execute(sa.text("UPDATE messages SET ref = :ref WHERE id = :id"),
                     {"ref": _encode_ref(int(n)), "id": message_id})

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_settings_calendar_token'), 'user_settings', type_='unique')
    op.drop_column('user_settings', 'onboarding_dismissed')
    op.drop_column('user_settings', 'test_alert_at')
    op.drop_column('user_settings', 'calendar_token')
    op.drop_column('user_settings', 'deadlines_enabled')
    op.drop_column('user_settings', 'last_recap_at')
    op.drop_column('user_settings', 'weekly_recap')
    op.drop_column('user_settings', 'muted_senders')
    op.drop_column('rules', 'source')
    op.drop_constraint(op.f('fk_outbound_emails_reply_to_message_id_messages'), 'outbound_emails', type_='foreignkey')
    op.drop_column('outbound_emails', 'provider_thread_id')
    op.drop_column('outbound_emails', 'references')
    op.drop_column('outbound_emails', 'in_reply_to')
    op.drop_column('outbound_emails', 'reply_to_message_id')
    op.drop_index('ix_messages_user_ref', table_name='messages')
    op.drop_column('messages', 'ref')
    op.drop_index('ix_events_user_starts', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
